bboard/urls.py
from django.urls import path, reverse_lazy
from django.contrib import admin
from django.contrib.auth.views import ( LoginView,LogoutView,
	PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
	PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from .views import (add_and_save, update, detail,
	by_rubric, index, delete, rubric, registerUser, showfiles, search, deleteimg)

app_name = 'bboard'
urlpatterns = [
	#path('deleteimg/<int:pk>/', deleteimg, name="deleteimg"),
	#path('test_cookie/', test_cookie, name='test_cookie'),
	path('search/', search, name='search'),
	path('showfiles/', showfiles, name='showfiles'),
	path('add/', add_and_save,
		name='add'),
	path('update/<int:pk>/', update,
		name='update'),
	path('delete/<int:pk>/', delete,
		name='delete'),
	path('rub_delete/', rubric,
		name='rub_delete'),
	path('detail/<int:pk>/', detail,
		name='detail'),
	path('<int:rubric_id>/', by_rubric,
		name='by_rubric'),
	path('accounts/login/', LoginView.as_view(),
		name='login'),
	path('accounts/logout/', LogoutView.as_view(
		next_page='bboard:index'),
		name='logout'),
	path('accounts/password_change/', PasswordChangeView.as_view(
		success_url=(reverse_lazy('bboard:password_change_done')),
		template_name='registration/change_password.html'),
		name='password_change'),
	path('accounts/password_change/done/', PasswordChangeDoneView.as_view(),
		name='password_change_done'),
	path('accounts/password_reset/', PasswordResetView.as_view(
		success_url=(reverse_lazy('bboard:password_reset_done')),
		template_name='registration/reset_password.html',
		subject_template_name='registration/reset_subject.txt',
		email_template_name='registration/reset_email.html'),
		name='password_reset'),
	path('accounts/password_reset/done/', PasswordResetDoneView.as_view(
		template_name='registration/email_sent.html'),
		name='password_reset_done'),
	path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
		success_url=(reverse_lazy('bboard:password_reset_complete')),
		template_name='registration/confirm_password.html'),
		name='password_reset_confirm'),
	path('accounts/reset/done/', PasswordResetCompleteView.as_view(
		template_name='registration/password_confirmed.html'),
		name='password_reset_complete'),
	path('register_user/', registerUser,
		name='register'),
	path('', index, name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace='')),
    path('captcha/', include('captcha.urls')),
    path('social/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/models.py
from django.db import models
from datetime import datetime
from os.path import splitext
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.dispatch import Signal
from django.utils.safestring import mark_safe

add_rubric = Signal(providing_args=['created','instance'])

def get_timestamp_path(instance, filename):
	return '%s%s%s' % ('archives/%Y/%m/%d/', datetime.now().timestamp(), splitext(filename)[1])

#Дополнение к модели User
# class Profile(models.Model):
# 	phone = models.CharField(max_length = 12, verbose_name = 'Номер телефона')
# 	user = models.OneToOneField(User, on_delete = models.CASCADE)

#Дистпечер записей Рубрики
class RubricManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().order_by('name')
	def order_by_bd_count(self):
		return super().get_queryset().annotate(cnt=models.Count('bd')).order_by('-cnt')

#Диспетчер записи вторичной модели(Bd)
class BdManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().order_by('-published')

#Рубрика
class Rubric(models.Model):
	name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
	def __str__(self):
		return self.name
	class Meta:
		verbose_name_plural = 'Рубрики'
		verbose_name = 'Рубрика'
		ordering = ['name']
	objects = RubricManager()

#Посты 
class Bd(models.Model):
	title = models.CharField(max_length=50, verbose_name='Товар')
	content = models.TextField(null=True, blank=True, verbose_name='Описание')
	price = models.FloatField(null=True, blank=True, default=0, verbose_name='Цена')
	published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
	rubric = models.ForeignKey('Rubric', null=True,
		on_delete=models.CASCADE, verbose_name='Рубрика')
	class Meta:
		verbose_name_plural='Объявления'
		verbose_name='Объявление'
		ordering=['-published']
	objects = models.Manager()
	reverse = BdManager()

#Фото связанная с Bd как расширение изображений 
class Img(models.Model):
	class Meta:
		verbose_name = 'Изображение'
		verbose_name_plural = 'Изображения'
	img = models.ImageField(verbose_name='Изображение', null=False, help_text='150x150px', upload_to = 'archives/%Y/%m/%d/')
	bd = models.OneToOneField(Bd, on_delete=models.CASCADE)

#Файлы
class File(models.Model):
	file = models.FileField(verbose_name='Файл')
	desc = models.TextField(verbose_name='Описание')
	class Meta:
		verbose_name = 'Файл'
		verbose_name_plural = 'Файлы'


#Сигналы обрпботки данных
def post_save_dispatcher(sender, **kwargs):
	if kwargs['created']:
		#print(kwargs)
		print('Объявление в рубрике "%s" создано' % kwargs['instance'].rubric.name)
post_save.connect(post_save_dispatcher, sender=Bd)

def post_delete_dispatcher(sender, **kwargs):
	print('Запись "%s" была удалена' % kwargs['instance'].title)
post_delete.connect(post_delete_dispatcher, sender=Bd)

# def add_rubric_dispatcher(sender, **kwargs):
# 	if kwargs['created']:
# 		print('Добавлена рубрика "%s"' % kwargs['instance'])
# 		print(kwargs['instance'])
# add_rubric.connect(add_rubric_dispatcher, sender=Rubric)

bboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core import validators
from django.forms import modelform_factory, DecimalField, formset_factory
from django.forms.widgets import Select
from django.core.exceptions import ValidationError
#from captcha.fields import CaptchaField

from .models import Bd, Rubric, Img, File

# Форма связанная с моделю хранится в памяти и полезно для постоянного вызова формы
class BdForm(forms.ModelForm):
	#Валидация 
	# def clean(self):
	# 	super().clean()
	# 	errors = {}
	# 	if not self.content:
	# 		errors['content'] = ValidationError('Укажите описание товара')
	# 	if self.price < 0:
	# 		errors['price'] = ValidationError('Цена не может быть отрицательная')
	# 	elif errors:
	# 		raise ValidationError(errors)
	#Поля
	title = forms.CharField(label = 'Название товара')
	content = forms.CharField(label = 'Описание товара',
			# validators=[validators.RegexValidator(regex='^.{4,}$')],
			# error_messages={'invalid': 'Слишком короткое описание'},
			widget = forms.widgets.Textarea())
	price = forms.DecimalField(label = 'Цена', decimal_places=2)
	rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(),
			label = 'Рубрика', help_text = 'Не забудьте Рубрику')
	# photo = forms.ImageField(
	# 	label='Изображение',
	# 	# validators=[validators.FileExtensionValidator(
	# 	# allowed_extensions=('gif', 'jpg', 'png'))],
	# 	# error_messages={'invalid_extension':'Этот формат файлов'+\
	# 	# 	'не поддерживается'},
	# 	widget=forms.widgets.ClearableFileInput(attrs={'multiple':True}))

	
	#captcha = CaptchaField()
	class Meta:
		model = Bd
		fields = ('title', 'content', 'price', 'rubric')

#Форма для фото
class ImgForm(forms.ModelForm):
	img = forms.ImageField(
		label='Изображение',
		required=False,
		widget=forms.widgets.ClearableFileInput(attrs={'multiple':True}))

	class Meta:
		model = Img
		fields = ('img',) 

# Форма регистрации для пользователя(контролер и модель пока отсутсвует)
class RegisterForm(forms.ModelForm):
	username = forms.CharField(label='Ваше имя', required=True)
	email = forms.EmailField(label='Ваш почтовый адрес', required=True)
	password1 = forms.CharField(strip=False, label='Ваш пароль', required=True )
	password2 = forms.CharField(strip=False, label='Повторите пароль', required=True)
	class Meta:
		model = User
		fields = ["username", "email", "password1", "password2"]

#Форма не связаная с моделью
class SearchForm(forms.Form):
	keyword = forms.CharField(max_length=20, required=False, error_messages=None)


# class ImgNotModelForm(forms.Form):
# 	img = forms.ImageField(
# 		label='Изображение',
# 		validators=[validators.FileExtensionValidator(
# 		allowed_extensions=('gif', 'jpg', 'png')
# 		)],
# 		error_messages={'invalid_extension':'Этот формат файлов'+\
# 		'не поддерживается'},
# 		widget=forms.widgets.ClearableFileInput(attrs={'multiple':True}))
# 	bd_id = forms.ModelChoiceField(
# 		queryset = Bd.objects.get(pk=later))	

class FileForm(forms.ModelForm):
	img = forms.FileField(
		label='Файл')
	desc = forms.CharField(label='Описание', widget=forms.widgets.Textarea())
	class Meta:
		model = Img
		fields = '__all__'

#Фабрика формы не связаная с моделью
#fs = formset_factory(SearchForm, extra = 3, can_delete = True)

bboard/views.py
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.urls.base import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.views.generic import edit, base, list, dates
from django.forms import modelformset_factory
from django.contrib import messages
from django.template import RequestContext
from django.dispatch import Signal
from django.core.mail import EmailMessage, get_connection, send_mail, get_connection,send_mass_mail
from django.template.loader import render_to_string
from django.views.decorators.vary import vary_on_headers, vary_on_cookie
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from precise_bbcode.bbcode import get_parser
from samplesite.settings import BASE_DIR
from datetime import datetime
import os
import ipdb

from .models import Bd, Rubric, Img, add_rubric
from .forms import BdForm, RegisterForm, SearchForm, ImgForm
CRITICAL = 50
FILES_ROOT = os.path.join(BASE_DIR, 'files')

#Главная страница с пагинаторомs
#@vary_on_cookie
def index(request):
	rubrics = Rubric.objects.all()
	bds = Bd.objects.all()
	bdp = set()
	for e in bds:
		i = Img.objects.filter(bd_id=e.pk).first()
		print(i, 'Проверка фото')
		bdp.add(i)
	print(bdp, 'Набор set')
	paginator = Paginator(bds, 10)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1
	page = paginator.page(page_num)
	if 'last_connection' in request.COOKIES:
		visits = int(request.COOKIES['last_connection']) + 1
	else:
		visits = 1
	context = {'rubrics':rubrics, 'img':bdp, 'page': page, 'bds': page.object_list, 'visits':visits}
	response = HttpResponse(render(request, 'bboard/index.html', context))
	response.set_cookie('last_connection', visits)
	return response

# Изменение/добавление/удаление рубрики
def rubric(request):
	RubricFormSet = modelformset_factory(Rubric, fields=('name',),
		can_order=True, can_delete=True)
	if request.method == "POST":
		formset = RubricFormSet(request.POST)
		if formset.is_valid():
			formset.save()
			return redirect('bboard:index')
	else:
		formset = RubricFormSet()
		context = {'formset':formset}
		return render(request, 'bboard/rubrics.html', context)

# Удаление записи 
def delete(request, pk):
	rubrics = Rubric.objects.all()
	if request.user.is_superuser:
		bd = Bd.objects.get(pk=pk)
		if request.method == 'POST':
			bd.delete()
			return HttpResponseRedirect(reverse('bboard:by_rubric',
				kwargs={'rubric_id': bd.rubric.pk}))
		else:
			context = {'bd': bd, 'rubrics':rubrics}
			return render(request, 'bboard/bd_delete.html', context)
	else:
		return HttpResponseForbidden('У вас нет доступа к этой странице')

#Изменение записи с посредством формы связаной с моделью
def update(request, pk, *args, **kwargs):
	rubrics = Rubric.objects.all()
	if request.user.is_superuser or request.user.is_staff:
		bd = Bd.objects.get(pk=pk)
		picture = Img.objects.filter(bd_id=bd.pk)
		if request.method == 'POST':
			bdf = BdForm(request.POST, instance=bd)
			bdp = ImgForm(request.POST, request.FILES)
			photo = picture
			if bdf.is_valid() and bdp.is_valid():
				id = bdf.save().pk
				for f in request.FILES.getlist('img'):
					img = Img()
					img.bd = Bd(pk=bd.pk)
					img.img = f
					img.save()
				messages.add_message(request, messages.SUCCESS, 'Обявление измнено успешно', extra_tags='first second')
				return HttpResponseRedirect(reverse('bboard:by_rubric',
					kwargs={'rubric_id': bdf.cleaned_data['rubric'].pk}))
			else:
				context = {'form':bdf,'picture':picture, 'formimg':bdp, 'rubrics':rubrics}
				return render(request, 'bboard/bd_update.html', context)
		else:
			bdf = BdForm(instance=bd)
			bdp = ImgForm()
			photo = picture
			context = {'form':bdf,'picture':picture, 'formimg':bdp,'rubrics':rubrics}
			return render(request, 'bboard/bd_update.html', context)
	else:
		return HttpResponseForbidden('У вас нет доступа')

#Самописный контроллер для отдельной записи
def detail(request, pk):
	bd = Bd.objects.get(pk=pk)
	img = Img.objects.filter(bd_id=bd.pk)
	print('проверка наличия объектов',img)
	rubrics = Rubric.objects.all()
	context = { 'bd':bd,'img':img, 'rubrics':rubrics}
	return render(request, 'bboard/bd_detail.html', context)

#Все рубрики
def by_rubric(request, rubric_id):
	bds = Bd.objects.filter(rubric=rubric_id)
	rubrics = Rubric.objects.order_by_bd_count()
	current_rubric = Rubric.objects.get(pk=rubric_id)
	img = set()
	for i in bds:
		image = Img.objects.filter(bd_id=i.pk).first()
		img.add(image)
	context = {'bds': bds, 'rubrics': rubrics, 'img' : img, 'current_rubric': current_rubric}
	return render(request, 'bboard/by_rubric.html', context)

#Сохрание записи в базе данных 
def add_and_save(request):
	rubrics = Rubric.objects.all()
	if request.user.is_authenticated:
		if request.method == 'POST':
			bdf = BdForm(request.POST)
			bdp = ImgForm(request.POST, request.FILES)
			if bdf.is_valid() and bdp.is_valid():
				id = bdf.save().pk
				#parent = Bd.objects.get(pk=id)
				for f in request.FILES.getlist('img'):
					img = Img()
					img.bd = Bd(pk=id)
					img.img = f
					img.save()
				return HttpResponseRedirect(reverse('bboard:by_rubric',
					kwargs={'rubric_id': bdf.cleaned_data['rubric'].pk}))
			else:
				contex = {'form':bdf, 'formimg':bdp, 'rubrics': rubrics}
				return render(request, 'bboard/create.html', contex)
		else:
			bdf = BdForm
			bdp = ImgForm
			contex = {'form': bdf, 'formimg': bdp,'rubrics': rubrics}
			return render(request, 'bboard/create.html', contex)
	else:
		return HttpResponseForbidden('У вас нет доступа')

#Регистрация пользователя
def registerUser(request):
	rubrics = Rubric.objects.all()
	form = RegisterForm(request.POST)
	if request.method == "POST":
		if form.is_valid():
			send_mail('Test', 'test!', 'webmaster@samplesite.ru', ['user@site.ru'], html_message='<h1>HEllo loshok</h1>')
			form.save()
			return HttpResponseRedirect(reverse('bboard:login'))
		else:
			contex = {'form': form, 'rubrics': rubrics}
			return render(request, 'registration/register_user.html', contex)
	else:
		contex = {'form': form, 'rubrics': rubrics}
		return render(request, 'registration/register_user.html', contex)

#Поисковая система
def search(request):
	if request.method == 'POST':
		form = request.POST.get('search')
		bds = Bd.objects.filter(title__istartswith=form.strip())
		if not bds:
			context = {'text': 'По вашему запросу ничего не найдено!'}
		else:
			context = {'bds': bds}
		return render(request, 'bboard/search_result.html', context)
	
	
#Вывод загружунных файлов
def showfiles(request):
	img = Img.objects.all()
	context = {'imgs': img}
	return render(request, 'bboard/files.html', context)

#Удаление фото
def deleteimg(request, pk):
	img = Img.objects.get(pk=pk)
	img.img.delete()
	img.delete()
	return redirect('bboard:index')

#Отправка сигнала в консоль при добавление рубрики 
add_rubric.send(Rubric, created = True, instance = rubric)

#Отправка электронного письма без вложений
# em = EmailMessage(subject = 'Test', body = 'Test', to = ['butajiuk6@gmail.com'])
# em.send()

#Отправка письма с вложеном пароле
# em = EmailMessage(subject='Ваш новый пароль',
# 	body = 'Ваш новый пароль находится во вложении',
# 	attachments = [('password.txt', '123456789', 'tex/plain')],
# 	to = ['butajiuk6@gmail.com'])
# em.send()

#Отправка электронной почты с вложение хранящийся на локальном диске
# em = EmailMessage(subject = 'Запрошеный вами файл', body = 'Сам файл', to = ['butajiuk6@gmail.com'])
# em.attach_file(r'C:\User\admin\desktop\file.txt')
# em.send()

#Отправка почты с помощью шаблона django
# context = {'user':'Вася Пупкин'}
# s = render_to_string('email/letter.txt', context)
# em = EmailMessage(subject = 'Оповещение', body = s, to = ['vpupkin@mail.ru'])
# em.send()

#Отправка множество писем с разовым подключением к серверу SMTP 
# cn = get_connection()
# cn.open()
# email1 = EmailMessage(..., connection=cn)
# email1.send()
# email2 = EmailMessage(..., connection=cn)
# email2.send()
# cn.close()

#Отправка перечь писем
# msg1 = send_mass_mail('Подписка','Потверждение подписки', 'admin@site.ru', ['user@site.ru'])
# msg2 = send_mass_mail('Одобрение', 'Ваша подписка потверждена', 'admin@site.ru', ['user@site.ru'])
# send_mass_mail(msg1, msg2)

bboard/templates/bboard/bd_archive_month.html
{% extends 'layout/basic.html' %}

{% block contex %}
{% for bd in object_list %}
<div class="b">
	<h1><a href="{% url 'bboard:detail' pk=bd.pk %}">{{ bd.year }}</a></h1>
	<p>{{ bd.content }}</p>
	<p><a href="{% url 'bboard:update' pk=bd.pk %}">Изменить</a></p>
	<p><a href="{% url 'bboard:delete' pk=bd.pk %}">Удалить</a></p>
{% endfor %}
	
{% endblock contex %}

bboard/templates/bboard/bd_delete.html
{% extends 'layout/basic.html' %}

{% block title %}Удаление товара {{ bd.title }}{% endblock title %}

{% block content %}
<h1>Удаление записи</h1>
<p>Рубрика: {{ bd.rubric.name }}</p>
<p>Товар: {{ bd.title }}</p> 
<p>Описание: {{ bd.content }}</p>
<p>Цена: {{ bd.price }}</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Удаление" class="btn btn-success">
</form>
{% endblock content %}

bboard/templates/bboard/bd_detail.html
{% extends "layout/basic.html" %}
{% load my_templatetags %}
{% load thumbnail %}

{% block title %}{{ bd.title }}{% endblock %}
{% block content %}

<div class="card mb-3">
  {% for i in img %}
    <img src="{{ i.img|thumbnail_url:'default' }}">
  {% endfor %}
  <div class="card-body">
    <h5 class="card-title">{{ bd.title }}</h5>
    <p class="card-text">{{ bd.content }}</p>
    <p class="card-text">{{ bd.price|currency }}</p>
    <p class="card-text">Дата: {{ bd.published|date:"d.m.Y H:i:s" }}</p>
  </div>
    {% if user.is_superuser %}
      <ul><a href="{% url 'bboard:update' pk=bd.pk %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true"> Изменить</a></ul> 
      <ul><a href="{% url 'bboard:delete' pk=bd.pk %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Удалить Запись</a></ul>
      {% comment %} <ul><a href="{% url 'bboard:deleteimg' pk=bd.pk %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Удалить Фото</a></ul> {% endcomment %}
    {% endif %}
    <p>Эту страницу просмторели {{ visits }}</p>
</div>
{% endblock content %}

bboard/templates/bboard/bd_update.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% load thumbnail %}


{% block title %}Изменить объявление{% endblock %}

{% block content %}

<h2>Реактирование</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% for p in picture %}
		{% comment %} <img src="{{ p.img|thumbnail_url:'default' }}" width="100">
		<button type="button" class="btn btn-default btn-xs">X</button> {% endcomment %}
		<div style="position: relative; left: 0; top: 0;">
			<img src="{{ p.img|thumbnail_url:'default' }}" style="position: relative; top: 0; left: 0;"/>
			<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS4VbaLGoKcbJZuAMbe7t1Gixa0oqurMd07xiiL453GDB3kGVsa5C_4MQ" style="position: absolute; margin-top: 0px; margin-right: 0px;cursor:pointer;" width="20" height="20"/>
		</div>
	{% endfor %}
	{{ formimg|crispy }}
	<input type="submit" value="Изменить" class="btn btn-success">
</form>
{% endblock %}

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}
{% load thumbnail %}
{% block title %}{{ current_rubric.name }}{% endblock %}
{% load cache %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>

{% if messages %}
	<ul class="messages">
	{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
		{{ message }}
		</li>
	{% endfor %}
	</ul>
{% endif %}

<div class="row row-cols-1 row-cols-md-3">
  {% for bd in bds %}
    <div class="col mb-4">
      <div class="card">
      {% for i in img %}
        {% if i.bd_id == bd.pk %}
          <img  src="{{ i.img|thumbnail_url:'default' }}" class="card-img-top">
        {% endif %}
      {% endfor %}
          <div class="card-body">
            <h2><a href="{% url 'bboard:detail' pk=bd.pk %}">{{ bd.title }}</a></h2>
            <p>{{ bd.content }}</p>
            <p>{{ bd.published|date:"d.m.Y H:i:s" }}</p>
            <h6 class="card-subtitle mb-2 text-muted">{{ bd.rubric}}</h6>
            <a href="{% url 'bboard:detail' pk=bd.pk %}" class="card-link">Подробнее</a>
          </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block title %}Добавить объявление{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>
<div class='form_group_class'>
	<form  action="{% url 'bboard:add' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		{{ formimg|crispy }}
		<input type="submit" value="Создать" class="btn btn-success">
	</form>
</div>
{% endblock %}

bboard/templates/bboard/files.html
{% extends 'layout/basic.html' %}

{% block title %}
Вывод файлов
{% endblock title %}

{% block content %}
    {% for img in imgs %}
        <div><img src="{{ img.img.url }}"></div>
        <div><a href="{{ 'img' }}">Загрузить картинку</a></div>
    {% endfor %}
{% endblock content %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}
{% load thumbnail %}

{% block content %}

<p>Просмотры страницы {{ visits}}</p>
<div class="row row-cols-1 row-cols-md-3">
  {% for bd in bds %}
    <div class="col mb-4">
      <div class="card">
        {% for i in img %}
          {% if i.bd_id == bd.pk %}
            <img src="{{ i.img|thumbnail_url:'default' }}" class="card-img-top">
          {% endif %}
        {% endfor %}
          <div class="card-body">
            <h5 class="card-title">{{ bd.title }}</h5>
            <p class="card-text">{{ bd.content }}</p>
            <p class="card-subtitle mb-2 text-muted">{{ bd.rubric}}</p>
            <a href="{% url 'bboard:detail' pk=bd.pk %}" class="card-link">Подробнее</a>
          </div>
      </div>
    </div>
  {% endfor %}
</div>
<ul>
  <div class="pagination">
    {% comment %} <nav aria-label="Page navigation example"> {% endcomment %}
      <ul class="pagination">
          {% if page.has_previous %}
              <li class="page-item"><a class="page-link" href="?page=1">Начало</a></li>
              {% comment %} <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Назад</a></li> {% endcomment %}
          {% endif %}

          {% for number in page.paginator.page_range %}
            <li class="page-item"><a class="page-link active" href="?page={{ number }}">{{  number  }}</a></li>
          {% endfor %}
          {% if page.has_next %}
              {% comment %} <li class="page-item"><a href="?page={{ page.next_page_number }}" class="page-link">Далее</a></li> {% endcomment %}
              <li class="page-item"><a href="?page={{ page.paginator.num_pages }}" class="page-link">Конец</a></li>
          {% endif %}
      </ul>
    {% comment %} </nav> {% endcomment %}
  </div>
</ul>
{% endblock %}

bboard/templates/bboard/rubrics.html
{% extends 'layout/basic.html' %}

{% block title %}Изменить рубрику{% endblock %}

{% block content %}
<h2>Изменить/Добавить/Удалить рубрику</h2>
<form  action="{% url 'bboard:rub_delete'  %}" method="POST">
	{% csrf_token %}
	{{ formset.as_p }}
	<input type="submit" value="Применить">
</form>
{% endblock %}

bboard/templates/bboard/search_result.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% block title %}Результат поиска
{% endblock title %}

{% block content %}
<ul>
    <div>{% if bds %}
            {% for bd in bds %}
                <div class="col-md-4">
                <img src="{{ bd.photo|thumbnail_url:'default' }}">
                </div>
                <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ bd.title }}</h5>
                    <p class="card-text">{{ bd.content }}</p>
                    <h6 class="card-subtitle mb-2 text-muted">{{ bd.rubric}}</h6>
                    <a href="{% url 'bboard:detail' pk=bd.pk %}" class="card-link">Подробнее</a>
                </div>
                </div>
            {% endfor %}
        {% endif %}
        {% if not bds  %}
            <div class="alert alert-warning" role="alert">
                {{ text }}
            </div>
        {% endif %}
    </div>
</ul>
{% endblock content %}

bboard/templates/bboard/success.html
{% extends 'layout/basic.html' %}

{% block content %}

<h1>Записиь удалена</h1>
<a href='{%  url 'bboard:index' %}'> На главную</a>
{% endblock content %}